# Generated by Django 3.0.4 on 2021-10-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbRecoveryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redata_start_time', models.DateTimeField(blank=True, null=True, verbose_name='脱敏开始时间 1')),
                ('sensitive_type', models.CharField(blank=True, choices=[('1', '有敏感信息-脱敏'), ('2', '有敏感信息-不脱敏'), ('3', '无敏感信息')], default='3', help_text='敏感信息类型', max_length=10, null=True, verbose_name='敏感信息类型')),
                ('oa_number', models.CharField(blank=True, help_text='OA编号', max_length=20, null=True, verbose_name='OA编号')),
                ('data_extract_list', models.FileField(blank=True, help_text='数据提取单', null=True, upload_to='file/%Y/%m/%d', verbose_name='数据提取单')),
                ('sensitive_info_form', models.FileField(blank=True, help_text='敏感信息表', null=True, upload_to='file/%Y/%m/%d', verbose_name='敏感信息表')),
                ('oa_info_list', models.FileField(blank=True, help_text='oa稿签表', null=True, upload_to='file/%Y/%m/%d', verbose_name='oa稿签表')),
            ],
        ),
        migrations.CreateModel(
            name='EnvCreateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(blank=True, help_text='项目编号', max_length=30, null=True, verbose_name='项目编号')),
                ('requirement_number', models.CharField(blank=True, help_text='需求编号', max_length=30, null=True, verbose_name='需求编号')),
                ('file_content_resource', models.FileField(blank=True, help_text='资源规划表', null=True, upload_to='file/%Y/%m/%d', verbose_name='资源规划表')),
                ('file_content_request', models.FileField(blank=True, help_text='资源申请表', null=True, upload_to='file/%Y/%m/%d', verbose_name='资源申请表')),
                ('is_standard', models.BooleanField(blank=True, default=False, help_text='是否标准交付', null=True, verbose_name='是否标准交付')),
            ],
            options={
                'verbose_name': '环境新建详情',
                'verbose_name_plural': '环境新建详情',
            },
        ),
        migrations.CreateModel(
            name='FaultResolveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostenvs', models.CharField(blank=True, help_text='所有故障主机', max_length=500, null=True, verbose_name='所有故障主机')),
                ('priority', models.CharField(blank=True, choices=[('1', '普通'), ('2', '紧急')], help_text='紧急程度', max_length=10, null=True, verbose_name='紧急程度')),
                ('fault', models.CharField(blank=True, choices=[('1', '普通'), ('2', '紧急')], help_text='故障类型', max_length=10, null=True, verbose_name='故障类型')),
                ('cause', models.TextField(blank=True, help_text='根本类型', max_length=50, null=True, verbose_name='根本类型')),
                ('screenshot', models.FileField(blank=True, help_text='故障截图', null=True, upload_to='file/%Y/%m/%d', verbose_name='故障截图')),
            ],
            options={
                'verbose_name': '故障解决详情',
                'verbose_name_plural': '故障解决详情',
            },
        ),
        migrations.CreateModel(
            name='SubWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='子工单号', max_length=30, unique=True, verbose_name='子工单号')),
                ('status', models.CharField(choices=[('1', '新建待提交'), ('2', '处理中'), ('3', '已完成'), ('4', '已关闭')], default='0', help_text='子工单状态', max_length=30, verbose_name='子工单状态')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('content', models.TextField(blank=True, help_text='工单内容', null=True, verbose_name='工单内容')),
                ('execution', models.TextField(blank=True, help_text='完成情况', null=True, verbose_name='工单内容')),
            ],
            options={
                'verbose_name': '子工单信息',
                'verbose_name_plural': '子工单信息',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='工单号', max_length=30, unique=True, verbose_name='工单号')),
                ('title', models.CharField(help_text='工单标题', max_length=30, unique=True, verbose_name='工单标题')),
                ('content', models.CharField(help_text='工单内容', max_length=30, unique=True, verbose_name='工单内容')),
                ('type', models.CharField(choices=[('1', '环境申请'), ('2', '数据恢复'), ('3', '故障处理'), ('4', '服务请求')], default='0', help_text='工单类型', max_length=30, verbose_name='工单类型')),
                ('status', models.CharField(choices=[('1', '待提交'), ('2', '待审核'), ('3', '执行中'), ('4', '待脱敏'), ('5', '脱敏中'), ('6', '已脱敏'), ('7', '待确认'), ('8', '已关闭')], default='0', help_text='工单状态', max_length=30, verbose_name='工单状态')),
                ('is_show', models.BooleanField(blank=True, default=True, verbose_name='是否显示')),
                ('is_return', models.BooleanField(blank=True, default=True, verbose_name='是否退回')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('expect_time', models.DateTimeField(blank=True, null=True, verbose_name='期望时间')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('target_time', models.DateTimeField(blank=True, null=True, verbose_name='目标时间')),
            ],
            options={
                'verbose_name': '工单信息',
                'verbose_name_plural': '工单信息',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDeliverRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '交付记录',
                'verbose_name_plural': '交付记录',
            },
        ),
    ]
